openapi: 3.0.3
info:
  contact:
    email: support@adyen.com
    name: Adyen Support
    url: https://support.adyen.com/
  description: "Hosted Onboarding provides endpoints for using the Hosted Onboarding\
    \ Page. The related entities include account holders only. \nFor more information,\
    \ refer to our [documentation](https://docs.adyen.com/platforms/onboarding-and-verification/hosted-onboarding-page).\n\
    ## Authentication\nTo connect to the HOP API, you must use basic authentication\
    \ credentials of your web service user. If you don't have one, please contact\
    \ the [Adyen Support Team](https://support.adyen.com/hc/en-us/requests/new). Then\
    \ use its credentials to authenticate your request, for example:\n\n```\ncurl\n\
    -U \"ws@MarketPlace.YourMarketPlace\":\"YourWsPassword\" \\\n-H \"Content-Type:\
    \ application/json\" \\\n...\n```\nNote that when going live, you need to generate\
    \ new web service user credentials to access the [live endpoints](https://docs.adyen.com/development-resources/live-endpoints).\n\
    \n## Versioning\nThe HOP API supports versioning of its endpoints through a version\
    \ suffix in the endpoint URL. This suffix has the following format: \"vXX\", where\
    \ XX is the version number.\n\nFor example:\n```\nhttps://cal-test.adyen.com/cal/services/Hop/v6/getOnboardingUrl\n\
    ```"
  termsOfService: https://www.adyen.com/legal/terms-and-conditions
  title: 'Adyen for Platforms: Hosted Onboarding'
  version: "6"
servers:
- url: https://cal-test.adyen.com/cal/services/Hop/v6
paths:
  /getOnboardingUrl:
    post:
      description: "Returns a link to a Hosted Onboarding Page (HOP) to be used by\
        \ a specific account holder. Each account holder represents a single sub-merchant.\n\
        \nFor more information on how to use HOP, refer to [Hosted Onboarding Page](https://docs.adyen.com/platforms/onboarding-and-verification/hosted-onboarding-page). "
      operationId: post-getOnboardingUrl
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetOnboardingUrlRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOnboardingUrlResponse'
          description: OK - the request has succeeded.
        "400":
          description: Bad Request - a problem reading or understanding the request.
        "401":
          description: Unauthorized - authentication required.
        "403":
          description: Forbidden - insufficient permissions to process the request.
        "422":
          description: Unprocessable Entity - a request validation error.
        "500":
          description: Internal Server Error - the server could not process the request.
      summary: Get a link to a Hosted Onboarding Page.
      x-groupName: Hosted Onboarding Page
      x-sortIndex: 1
components:
  schemas:
    ErrorFieldType:
      example:
        errorDescription: errorDescription
        errorCode: 0
        fieldType:
          fieldName: accountCode
          field: field
          shareholderCode: shareholderCode
      properties:
        errorCode:
          description: The validation error code.
          format: int32
          type: integer
        errorDescription:
          description: A description of the validation error.
          type: string
        fieldType:
          $ref: '#/components/schemas/FieldType'
    FieldType:
      example:
        fieldName: accountCode
        field: field
        shareholderCode: shareholderCode
      properties:
        field:
          description: The full name of the property.
          type: string
        fieldName:
          description: The type of the field.
          enum:
          - accountCode
          - accountHolderCode
          - accountHolderDetails
          - accountNumber
          - accountStateType
          - accountStatus
          - accountType
          - address
          - bankAccount
          - bankAccountCode
          - bankAccountName
          - bankAccountUUID
          - bankBicSwift
          - bankCity
          - bankCode
          - bankName
          - bankStatement
          - branchCode
          - businessContact
          - cardToken
          - checkCode
          - city
          - companyRegistration
          - country
          - countryCode
          - currency
          - currencyCode
          - dateOfBirth
          - description
          - destinationAccountCode
          - document
          - documentExpirationDate
          - documentIssuerCountry
          - documentIssuerState
          - documentName
          - documentNumber
          - documentType
          - doingBusinessAs
          - drivingLicence
          - drivingLicenceBack
          - drivingLicense
          - email
          - firstName
          - formType
          - fullPhoneNumber
          - gender
          - hopWebserviceUser
          - houseNumberOrName
          - iban
          - idCard
          - idCardBack
          - idCardFront
          - idNumber
          - identityDocument
          - individualDetails
          - lastName
          - legalBusinessName
          - legalEntity
          - legalEntityType
          - merchantAccount
          - merchantCategoryCode
          - merchantReference
          - microDeposit
          - name
          - nationality
          - originalReference
          - ownerCity
          - ownerCountryCode
          - ownerHouseNumberOrName
          - ownerName
          - ownerPostalCode
          - ownerState
          - ownerStreet
          - passport
          - passportNumber
          - payoutMethodCode
          - personalData
          - phoneCountryCode
          - phoneNumber
          - postalCode
          - primaryCurrency
          - reason
          - registrationNumber
          - returnUrl
          - schedule
          - shareholder
          - shareholderCode
          - socialSecurityNumber
          - sourceAccountCode
          - stateOrProvince
          - status
          - stockExchange
          - stockNumber
          - stockTicker
          - store
          - storeDetail
          - storeName
          - storeReference
          - street
          - taxId
          - tier
          - tierNumber
          - transferCode
          - unknown
          - value
          - virtualAccount
          - visaNumber
          - webAddress
          - year
          type: string
        shareholderCode:
          description: The code of the shareholder that the field belongs to. If empty,
            the field belongs to an account holder.
          type: string
    GetOnboardingUrlRequest:
      example:
        accountHolderCode: accountHolderCode
        editMode: true
        shopperLocale: shopperLocale
        platformName: platformName
        returnUrl: returnUrl
      properties:
        accountHolderCode:
          description: The account holder code you provided when you created the account
            holder.
          type: string
        editMode:
          description: Indicates if editing checks is allowed even if all the checks
            have passed.
          type: boolean
        platformName:
          description: The platform name which will show up in the welcome page.
          type: string
        returnUrl:
          description: The URL where the sub-merchant will be redirected back to after
            they complete the onboarding, or if their session times out. Maximum length
            of 500 characters. If you don't provide this, the sub-merchant will be
            redirected back to the default return URL configured in your platform
            account.
          type: string
        shopperLocale:
          description: "The language to be used in the page, specified by a combination\
            \ of a language and country code. For example, **pt-BR**. \n\nIf not specified\
            \ in the request or if the language is not supported, the page uses the\
            \ browser language. If the browser language is not supported, the page\
            \ uses **en-US** by default.\n\nFor a list supported languages, refer\
            \ to [Change the page language](https://docs.adyen.com/platforms/onboarding-and-verification/hosted-onboarding-page#change-page-language)."
          type: string
      required:
      - accountHolderCode
    GetOnboardingUrlResponse:
      example:
        redirectUrl: redirectUrl
        invalidFields:
        - errorDescription: errorDescription
          errorCode: 0
          fieldType:
            fieldName: accountCode
            field: field
            shareholderCode: shareholderCode
        - errorDescription: errorDescription
          errorCode: 0
          fieldType:
            fieldName: accountCode
            field: field
            shareholderCode: shareholderCode
        resultCode: resultCode
        pspReference: pspReference
      properties:
        invalidFields:
          description: Contains field validation errors that would prevent requests
            from being processed.
          items:
            $ref: '#/components/schemas/ErrorFieldType'
          type: array
        pspReference:
          description: The reference of a request. Can be used to uniquely identify
            the request.
          type: string
        redirectUrl:
          description: The URL to the Hosted Onboarding Page where you should redirect
            your sub-merchant. This URL must be used within 30 seconds and can only
            be used once.
          type: string
        resultCode:
          description: The result code.
          type: string
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-Key
      type: apiKey
    BasicAuth:
      scheme: basic
      type: http
x-groups:
- Hosted Onboarding Page
