openapi: 3.0.3
info:
  contact:
    email: support@adyen.com
    name: Adyen Support
    url: https://support.adyen.com/
  description: |-
    The Notification Configuration API provides endpoints for setting up and testing notifications that inform you of events on your platform, for example when a KYC check or a payout has been completed.

    For more information, refer to our [documentation](https://docs.adyen.com/platforms/notifications).
    ## Authentication
    To connect to the Notification Configuration API, you must use basic authentication credentials of your web service user. If you don't have one, contact our [Adyen Support Team](https://support.adyen.com/hc/en-us/requests/new). Then use its credentials to authenticate your request, for example:

    ```
    curl
    -U "ws@MarketPlace.YourMarketPlace":"YourWsPassword" \
    -H "Content-Type: application/json" \
    ...
    ```
    Note that when going live, you need to generate new web service user credentials to access the [live endpoints](https://docs.adyen.com/development-resources/live-endpoints).

    ## Versioning
    The Notification Configuration API supports versioning of its endpoints through a version suffix in the endpoint URL. This suffix has the following format: "vXX", where XX is the version number.

    For example:
    ```
    https://cal-test.adyen.com/cal/services/Notification/v6/createNotificationConfiguration
    ```
  termsOfService: https://www.adyen.com/legal/terms-and-conditions
  title: 'Adyen for Platforms: Notification Configuration API'
  version: "6"
servers:
- url: https://cal-test.adyen.com/cal/services/Notification/v6
paths:
  /createNotificationConfiguration:
    post:
      description: Creates a subscription to notifications informing you of events
        on your platform. After the subscription is created, the events specified
        in the configuration will be sent to the URL specified in the configuration.
        Subscriptions must be configured on a per-event basis (as opposed to, for
        example, a per-account holder basis), so all event notifications of a marketplace
        and of a given type will be sent to the same endpoint(s). A marketplace may
        have multiple endpoints if desired; an event notification may be sent to as
        many or as few different endpoints as configured.
      operationId: post-createNotificationConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNotificationConfigurationRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetNotificationConfigurationResponse'
          description: OK - the request has succeeded.
      summary: Subscribe to notifications.
      x-groupName: General
      x-sortIndex: 1
  /deleteNotificationConfigurations:
    post:
      description: This endpoint is used to delete an existing notification subscription
        configuration. After the subscription is deleted, no further event notifications
        will be sent to the URL that was in the subscription.
      operationId: post-deleteNotificationConfigurations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteNotificationConfigurationRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
          description: OK - the request has succeeded.
      summary: Delete an existing notification subscription configuration.
      x-groupName: General
      x-sortIndex: 6
  /getNotificationConfiguration:
    post:
      description: This endpoint is used to retrieve the details of the configuration
        of a notification subscription.
      operationId: post-getNotificationConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetNotificationConfigurationRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetNotificationConfigurationResponse'
          description: OK - the request has succeeded.
      summary: Retrieve an existing notification subscription configuration.
      x-groupName: General
      x-sortIndex: 2
  /getNotificationConfigurationList:
    post:
      description: This endpoint is used to retrieve the details of the configurations
        of all of the notification subscriptions in the marketplace of the executing
        user.
      operationId: post-getNotificationConfigurationList
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmptyRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetNotificationConfigurationListResponse'
          description: OK - the request has succeeded.
      summary: Retrieve a list of existing notification subscription configurations.
      x-groupName: General
      x-sortIndex: 3
  /testNotificationConfiguration:
    post:
      description: This endpoint is used to test an existing notification subscription
        configuration. For each event type specified, a test notification will be
        generated and sent to the URL configured in the subscription specified.
      operationId: post-testNotificationConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestNotificationConfigurationRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestNotificationConfigurationResponse'
          description: OK - the request has succeeded.
      summary: Test an existing notification configuration.
      x-groupName: General
      x-sortIndex: 4
  /updateNotificationConfiguration:
    post:
      description: This endpoint is used to update an existing notification subscription
        configuration. If updating the event types, all event types desired must be
        provided, otherwise the previous event type configuration will be overwritten.
      operationId: post-updateNotificationConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNotificationConfigurationRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetNotificationConfigurationResponse'
          description: OK - the request has succeeded.
      summary: Update an existing notification subscription configuration.
      x-groupName: General
      x-sortIndex: 5
components:
  schemas:
    CreateNotificationConfigurationRequest:
      example:
        configurationDetails:
          hmacSignatureKey: hmacSignatureKey
          apiVersion: 0
          eventConfigs:
          - includeMode: EXCLUDE
            eventType: ACCOUNT_CLOSED
          - includeMode: EXCLUDE
            eventType: ACCOUNT_CLOSED
          notifyUsername: notifyUsername
          active: true
          description: description
          notifyURL: notifyURL
          sslProtocol: SSL
          notificationId: 6
          notifyPassword: notifyPassword
      properties:
        configurationDetails:
          $ref: '#/components/schemas/NotificationConfigurationDetails'
      required:
      - configurationDetails
    DeleteNotificationConfigurationRequest:
      example:
        notificationIds:
        - 0
        - 0
      properties:
        notificationIds:
          description: A list of IDs of the notification subscription configurations
            to be deleted.
          items:
            format: int64
            type: integer
          type: array
      required:
      - notificationIds
    EmptyRequest: {}
    ErrorFieldType:
      example:
        errorDescription: errorDescription
        errorCode: 1
        fieldType:
          fieldName: accountCode
          field: field
          shareholderCode: shareholderCode
      properties:
        errorCode:
          description: The validation error code.
          format: int32
          type: integer
        errorDescription:
          description: A description of the validation error.
          type: string
        fieldType:
          $ref: '#/components/schemas/FieldType'
    ExchangeMessage:
      example:
        messageCode: messageCode
        messageDescription: messageDescription
      properties:
        messageCode:
          type: string
        messageDescription:
          type: string
    FieldType:
      example:
        fieldName: accountCode
        field: field
        shareholderCode: shareholderCode
      properties:
        field:
          description: The full name of the property.
          type: string
        fieldName:
          description: The type of the field.
          enum:
          - accountCode
          - accountHolderCode
          - accountHolderDetails
          - accountNumber
          - accountStateType
          - accountStatus
          - accountType
          - address
          - bankAccount
          - bankAccountCode
          - bankAccountName
          - bankAccountUUID
          - bankBicSwift
          - bankCity
          - bankCode
          - bankName
          - bankStatement
          - branchCode
          - businessContact
          - cardToken
          - checkCode
          - city
          - companyRegistration
          - country
          - countryCode
          - currency
          - currencyCode
          - dateOfBirth
          - description
          - destinationAccountCode
          - document
          - documentExpirationDate
          - documentIssuerCountry
          - documentIssuerState
          - documentName
          - documentNumber
          - documentType
          - doingBusinessAs
          - drivingLicence
          - drivingLicenceBack
          - drivingLicense
          - email
          - firstName
          - formType
          - fullPhoneNumber
          - gender
          - hopWebserviceUser
          - houseNumberOrName
          - iban
          - idCard
          - idCardBack
          - idCardFront
          - idNumber
          - identityDocument
          - individualDetails
          - lastName
          - legalBusinessName
          - legalEntity
          - legalEntityType
          - merchantAccount
          - merchantCategoryCode
          - merchantReference
          - microDeposit
          - name
          - nationality
          - originalReference
          - ownerCity
          - ownerCountryCode
          - ownerHouseNumberOrName
          - ownerName
          - ownerPostalCode
          - ownerState
          - ownerStreet
          - passport
          - passportNumber
          - payoutMethodCode
          - personalData
          - phoneCountryCode
          - phoneNumber
          - postalCode
          - primaryCurrency
          - reason
          - registrationNumber
          - returnUrl
          - schedule
          - shareholder
          - shareholderCode
          - socialSecurityNumber
          - sourceAccountCode
          - stateOrProvince
          - status
          - stockExchange
          - stockNumber
          - stockTicker
          - store
          - storeDetail
          - storeName
          - storeReference
          - street
          - taxId
          - tier
          - tierNumber
          - transferCode
          - unknown
          - value
          - virtualAccount
          - visaNumber
          - webAddress
          - year
          type: string
        shareholderCode:
          description: The code of the shareholder that the field belongs to. If empty,
            the field belongs to an account holder.
          type: string
    GenericResponse:
      example:
        invalidFields:
        - errorDescription: errorDescription
          errorCode: 1
          fieldType:
            fieldName: accountCode
            field: field
            shareholderCode: shareholderCode
        - errorDescription: errorDescription
          errorCode: 1
          fieldType:
            fieldName: accountCode
            field: field
            shareholderCode: shareholderCode
        resultCode: resultCode
        pspReference: pspReference
      properties:
        invalidFields:
          description: Contains field validation errors that would prevent requests
            from being processed.
          items:
            $ref: '#/components/schemas/ErrorFieldType'
          type: array
        pspReference:
          description: The reference of a request. Can be used to uniquely identify
            the request.
          type: string
        resultCode:
          description: The result code.
          type: string
    GetNotificationConfigurationListResponse:
      example:
        invalidFields:
        - errorDescription: errorDescription
          errorCode: 1
          fieldType:
            fieldName: accountCode
            field: field
            shareholderCode: shareholderCode
        - errorDescription: errorDescription
          errorCode: 1
          fieldType:
            fieldName: accountCode
            field: field
            shareholderCode: shareholderCode
        configurations:
        - hmacSignatureKey: hmacSignatureKey
          apiVersion: 0
          eventConfigs:
          - includeMode: EXCLUDE
            eventType: ACCOUNT_CLOSED
          - includeMode: EXCLUDE
            eventType: ACCOUNT_CLOSED
          notifyUsername: notifyUsername
          active: true
          description: description
          notifyURL: notifyURL
          sslProtocol: SSL
          notificationId: 6
          notifyPassword: notifyPassword
        - hmacSignatureKey: hmacSignatureKey
          apiVersion: 0
          eventConfigs:
          - includeMode: EXCLUDE
            eventType: ACCOUNT_CLOSED
          - includeMode: EXCLUDE
            eventType: ACCOUNT_CLOSED
          notifyUsername: notifyUsername
          active: true
          description: description
          notifyURL: notifyURL
          sslProtocol: SSL
          notificationId: 6
          notifyPassword: notifyPassword
        resultCode: resultCode
        pspReference: pspReference
      properties:
        configurations:
          description: Details of the notification subscription configurations.
          items:
            $ref: '#/components/schemas/NotificationConfigurationDetails'
          type: array
        invalidFields:
          description: Contains field validation errors that would prevent requests
            from being processed.
          items:
            $ref: '#/components/schemas/ErrorFieldType'
          type: array
        pspReference:
          description: The reference of a request. Can be used to uniquely identify
            the request.
          type: string
        resultCode:
          description: The result code.
          type: string
      required:
      - configurations
    GetNotificationConfigurationRequest:
      example:
        notificationId: 0
      properties:
        notificationId:
          description: The ID of the notification subscription configuration whose
            details are to be retrieved.
          format: int64
          type: integer
      required:
      - notificationId
    GetNotificationConfigurationResponse:
      example:
        invalidFields:
        - errorDescription: errorDescription
          errorCode: 1
          fieldType:
            fieldName: accountCode
            field: field
            shareholderCode: shareholderCode
        - errorDescription: errorDescription
          errorCode: 1
          fieldType:
            fieldName: accountCode
            field: field
            shareholderCode: shareholderCode
        configurationDetails:
          hmacSignatureKey: hmacSignatureKey
          apiVersion: 0
          eventConfigs:
          - includeMode: EXCLUDE
            eventType: ACCOUNT_CLOSED
          - includeMode: EXCLUDE
            eventType: ACCOUNT_CLOSED
          notifyUsername: notifyUsername
          active: true
          description: description
          notifyURL: notifyURL
          sslProtocol: SSL
          notificationId: 6
          notifyPassword: notifyPassword
        resultCode: resultCode
        pspReference: pspReference
      properties:
        configurationDetails:
          $ref: '#/components/schemas/NotificationConfigurationDetails'
        invalidFields:
          description: Contains field validation errors that would prevent requests
            from being processed.
          items:
            $ref: '#/components/schemas/ErrorFieldType'
          type: array
        pspReference:
          description: The reference of a request. Can be used to uniquely identify
            the request.
          type: string
        resultCode:
          description: The result code.
          type: string
      required:
      - configurationDetails
    NotificationConfigurationDetails:
      example:
        hmacSignatureKey: hmacSignatureKey
        apiVersion: 0
        eventConfigs:
        - includeMode: EXCLUDE
          eventType: ACCOUNT_CLOSED
        - includeMode: EXCLUDE
          eventType: ACCOUNT_CLOSED
        notifyUsername: notifyUsername
        active: true
        description: description
        notifyURL: notifyURL
        sslProtocol: SSL
        notificationId: 6
        notifyPassword: notifyPassword
      properties:
        active:
          description: Indicates whether the notification subscription is active.
          type: boolean
        apiVersion:
          description: The API version of the notification to send.
          format: int32
          type: integer
        description:
          description: A description of the notification subscription configuration.
          type: string
        eventConfigs:
          description: The types of events whose notifications apply to this configuration.
          items:
            $ref: '#/components/schemas/NotificationEventConfiguration'
          type: array
        hmacSignatureKey:
          description: |-
            A string with which to salt the notification(s) before hashing. If this field is provided, a hash value will be included under the notification header `HmacSignature` and the hash protocol will be included under the notification header `Protocol`. A notification body along with its `hmacSignatureKey` and `Protocol` can be used to calculate a hash value; matching this hash value with the `HmacSignature` will ensure that the notification body has not been tampered with or corrupted.

            >Must be a 32-byte hex-encoded string (i.e. a string containing 64 hexadecimal characters; e.g. "b0ea55c2fe60d4d1d605e9c385e0e7f7e6cafbb939ce07010f31a327a0871f27").

            The omission of this field will preclude the provision of the `HmacSignature` and `Protocol` headers in notification(s).
          type: string
        notificationId:
          description: |-
            The ID of the configuration.
            >Required if updating an existing configuration, ignored during the creation of a configuration.
          format: int64
          type: integer
        notifyPassword:
          description: The password to use when accessing the notifyURL with the specified
            username.
          type: string
        notifyURL:
          description: The URL to which the notifications are to be sent.
          type: string
        notifyUsername:
          description: The username to use when accessing the notifyURL.
          type: string
        sslProtocol:
          description: |-
            The SSL protocol employed by the endpoint.
            >Permitted values: `SSL`, `SSLInsecureCiphers`, `TLS`, `TLSv10`, `TLSv10InsecureCiphers`, `TLSv11`, `TLSv12`.
          enum:
          - SSL
          - SSLInsecureCiphers
          - TLS
          - TLSv10
          - TLSv10InsecureCiphers
          - TLSv11
          - TLSv12
          type: string
      required:
      - eventConfigs
      - notifyURL
    NotificationEventConfiguration:
      example:
        includeMode: EXCLUDE
        eventType: ACCOUNT_CLOSED
      properties:
        eventType:
          description: |-
            The type of event triggering the notification.
            >Permitted values: `ACCOUNT_HOLDER_CREATED`, `ACCOUNT_CREATED`, `ACCOUNT_UPDATED`, `ACCOUNT_HOLDER_UPDATED`, `ACCOUNT_HOLDER_STATUS_CHANGE`, `ACCOUNT_HOLDER_STORE_STATUS_CHANGE`, `ACCOUNT_HOLDER_VERIFICATION`, `ACCOUNT_HOLDER_LIMIT_REACHED`, `ACCOUNT_HOLDER_PAYOUT`, `PAYMENT_FAILURE`, `SCHEDULED_REFUNDS`, `REPORT_AVAILABLE`, `TRANSFER_FUNDS`, `BENEFICIARY_SETUP`, `COMPENSATE_NEGATIVE_BALANCE`.
          enum:
          - ACCOUNT_CLOSED
          - ACCOUNT_CREATED
          - ACCOUNT_FUNDS_BELOW_THRESHOLD
          - ACCOUNT_HOLDER_CREATED
          - ACCOUNT_HOLDER_LIMIT_REACHED
          - ACCOUNT_HOLDER_PAYOUT
          - ACCOUNT_HOLDER_STATUS_CHANGE
          - ACCOUNT_HOLDER_STORE_STATUS_CHANGE
          - ACCOUNT_HOLDER_UPCOMING_DEADLINE
          - ACCOUNT_HOLDER_UPDATED
          - ACCOUNT_HOLDER_VERIFICATION
          - ACCOUNT_UPDATED
          - BENEFICIARY_SETUP
          - COMPENSATE_NEGATIVE_BALANCE
          - DIRECT_DEBIT_INITIATED
          - PAYMENT_FAILURE
          - REFUND_FUNDS_TRANSFER
          - REPORT_AVAILABLE
          - SCHEDULED_REFUNDS
          - TRANSFER_FUNDS
          type: string
        includeMode:
          description: |-
            Indicates whether the specified eventType is to be sent to the endpoint or all events other than the specified eventType (and other specified eventTypes) are to be sent.
            >Permitted values: `INCLUDE`, `EXCLUDE`.
            >- `INCLUDE`: send the specified eventType.
            >- `EXCLUDE`: send all eventTypes other than the specified eventType (and other eventTypes marked with `EXCLUDE`).
          enum:
          - EXCLUDE
          - INCLUDE
          type: string
      required:
      - eventType
      - includeMode
    TestNotificationConfigurationRequest:
      example:
        notificationId: 0
        eventTypes:
        - ACCOUNT_CLOSED
        - ACCOUNT_CLOSED
      properties:
        eventTypes:
          description: |-
            The event types to test.  If left blank, then all of the configured event types will be tested.
            >Permitted values: `ACCOUNT_HOLDER_CREATED`, `ACCOUNT_CREATED`, `ACCOUNT_UPDATED`, `ACCOUNT_HOLDER_UPDATED`, `ACCOUNT_HOLDER_STATUS_CHANGE`, `ACCOUNT_HOLDER_STORE_STATUS_CHANGE` `ACCOUNT_HOLDER_VERIFICATION`, `ACCOUNT_HOLDER_LIMIT_REACHED`, `ACCOUNT_HOLDER_PAYOUT`, `PAYMENT_FAILURE`, `SCHEDULED_REFUNDS`, `REPORT_AVAILABLE`, `TRANSFER_FUNDS`, `BENEFICIARY_SETUP`, `COMPENSATE_NEGATIVE_BALANCE`.
          items:
            enum:
            - ACCOUNT_CLOSED
            - ACCOUNT_CREATED
            - ACCOUNT_FUNDS_BELOW_THRESHOLD
            - ACCOUNT_HOLDER_CREATED
            - ACCOUNT_HOLDER_LIMIT_REACHED
            - ACCOUNT_HOLDER_PAYOUT
            - ACCOUNT_HOLDER_STATUS_CHANGE
            - ACCOUNT_HOLDER_STORE_STATUS_CHANGE
            - ACCOUNT_HOLDER_UPCOMING_DEADLINE
            - ACCOUNT_HOLDER_UPDATED
            - ACCOUNT_HOLDER_VERIFICATION
            - ACCOUNT_UPDATED
            - BENEFICIARY_SETUP
            - COMPENSATE_NEGATIVE_BALANCE
            - DIRECT_DEBIT_INITIATED
            - PAYMENT_FAILURE
            - REFUND_FUNDS_TRANSFER
            - REPORT_AVAILABLE
            - SCHEDULED_REFUNDS
            - TRANSFER_FUNDS
            type: string
          type: array
        notificationId:
          description: The ID of the notification subscription configuration to be
            tested.
          format: int64
          type: integer
      required:
      - notificationId
    TestNotificationConfigurationResponse:
      example:
        errorMessages:
        - errorMessages
        - errorMessages
        invalidFields:
        - errorDescription: errorDescription
          errorCode: 1
          fieldType:
            fieldName: accountCode
            field: field
            shareholderCode: shareholderCode
        - errorDescription: errorDescription
          errorCode: 1
          fieldType:
            fieldName: accountCode
            field: field
            shareholderCode: shareholderCode
        resultCode: resultCode
        exchangeMessages:
        - messageCode: messageCode
          messageDescription: messageDescription
        - messageCode: messageCode
          messageDescription: messageDescription
        okMessages:
        - okMessages
        - okMessages
        notificationId: 0
        eventTypes:
        - ACCOUNT_CLOSED
        - ACCOUNT_CLOSED
        pspReference: pspReference
      properties:
        errorMessages:
          description: Any error messages encountered.
          items:
            type: string
          type: array
        eventTypes:
          description: |-
            The event types that were tested.
            >Permitted values: `ACCOUNT_HOLDER_CREATED`, `ACCOUNT_CREATED`, `ACCOUNT_UPDATED`, `ACCOUNT_HOLDER_UPDATED`, `ACCOUNT_HOLDER_STATUS_CHANGE`, `ACCOUNT_HOLDER_STORE_STATUS_CHANGE` `ACCOUNT_HOLDER_VERIFICATION`, `ACCOUNT_HOLDER_LIMIT_REACHED`, `ACCOUNT_HOLDER_PAYOUT`, `PAYMENT_FAILURE`, `SCHEDULED_REFUNDS`, `REPORT_AVAILABLE`, `TRANSFER_FUNDS`, `BENEFICIARY_SETUP`, `COMPENSATE_NEGATIVE_BALANCE`.
          items:
            enum:
            - ACCOUNT_CLOSED
            - ACCOUNT_CREATED
            - ACCOUNT_FUNDS_BELOW_THRESHOLD
            - ACCOUNT_HOLDER_CREATED
            - ACCOUNT_HOLDER_LIMIT_REACHED
            - ACCOUNT_HOLDER_PAYOUT
            - ACCOUNT_HOLDER_STATUS_CHANGE
            - ACCOUNT_HOLDER_STORE_STATUS_CHANGE
            - ACCOUNT_HOLDER_UPCOMING_DEADLINE
            - ACCOUNT_HOLDER_UPDATED
            - ACCOUNT_HOLDER_VERIFICATION
            - ACCOUNT_UPDATED
            - BENEFICIARY_SETUP
            - COMPENSATE_NEGATIVE_BALANCE
            - DIRECT_DEBIT_INITIATED
            - PAYMENT_FAILURE
            - REFUND_FUNDS_TRANSFER
            - REPORT_AVAILABLE
            - SCHEDULED_REFUNDS
            - TRANSFER_FUNDS
            type: string
          type: array
        exchangeMessages:
          description: The notification message and related response messages.
          items:
            $ref: '#/components/schemas/ExchangeMessage'
          type: array
        invalidFields:
          description: Contains field validation errors that would prevent requests
            from being processed.
          items:
            $ref: '#/components/schemas/ErrorFieldType'
          type: array
        notificationId:
          description: The ID of the notification subscription configuration.
          format: int64
          type: integer
        okMessages:
          description: A list of messages describing the testing steps.
          items:
            type: string
          type: array
        pspReference:
          description: The reference of a request. Can be used to uniquely identify
            the request.
          type: string
        resultCode:
          description: The result code.
          type: string
      required:
      - eventTypes
      - exchangeMessages
      - notificationId
      - okMessages
    UpdateNotificationConfigurationRequest:
      example:
        configurationDetails:
          hmacSignatureKey: hmacSignatureKey
          apiVersion: 0
          eventConfigs:
          - includeMode: EXCLUDE
            eventType: ACCOUNT_CLOSED
          - includeMode: EXCLUDE
            eventType: ACCOUNT_CLOSED
          notifyUsername: notifyUsername
          active: true
          description: description
          notifyURL: notifyURL
          sslProtocol: SSL
          notificationId: 6
          notifyPassword: notifyPassword
      properties:
        configurationDetails:
          $ref: '#/components/schemas/NotificationConfigurationDetails'
      required:
      - configurationDetails
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-Key
      type: apiKey
    BasicAuth:
      scheme: basic
      type: http
x-groups:
- General
